### ISSUE TITLE
license request (e.g. MIT, BSD)

### ISSUE THREAD

**Issue by julienAhn** [RiccardoM3/IndoorPositioning#1]
Hello, 

My name is Julien, and I'm a master’s student at Aachen, Germany. I'm doing my master’s thesis in cooperation with a local IT company on the topic, "Smartphone-based indoor positioning for generating Wi-Fi heatmaps". I came across your GitHub repository when carrying out background research, and parts of your code would be a great starting point for my thesis! Since there is no license on the repo, I am unable to use it in my thesis. Would you be open to add a license model (e.g. MIT, BSD) on your repo so that I can use your code in my thesis? (If you are not familiar with the different types of licenses you can find a compact explanation here: https://www.freecodecamp.org/news/how-open-source-licenses-work-and-how-to-add-them-to-your-projects-34310c3cf94/.)

Thanks in advance! 
Cheers, 
Julien Ahn

FH Aachen: https://www.fh-aachen.de/en/faculties/electrical-engineering-and-information-technology/
Devolo: https://www.devolo.global/about-devolo/portrait

**Comment by RiccardoM3** [comment]
Hi Julien,

I've added an MIT license. 
Good luck in your thesis!

**Comment by julienAhn** [comment]
Great, thank you!
